services:
  kindle-dashboard:
    build: .
    ports:
      - "10876:8080" # Single server for both dashboard and battery updates
    volumes:
      - ./public:/app/public
    environment:
      LATITUDE: ${LATITUDE}
      LONGITUDE: ${LONGITUDE}
      TIMEZONE: ${TIMEZONE}
      LANGUAGE: ${LANGUAGE}
    restart: always
